# Generated by Django 4.2 on 2024-08-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('identification', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_order',
            fields=[
                ('id_purchase_order', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_client_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquorManagment.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_image', models.ImageField(upload_to='media/product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('available_stock', models.IntegerField()),
                ('Category_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquorManagment.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquorManagment.product')),
                ('purchase_order_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquorManagment.purchase_order')),
            ],
        ),
    ]
