# Generated by Django 4.2 on 2024-08-12 02:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liquorManagment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
